name: base
channels:
  - conda-forge
  - ome
dependencies:
  # - beakerx
  - pip
  - pygobject
  - gtk3
  - websockify
  - pyimagej
  - omero-py
  - jupyter-server-proxy
  - Cython
  - pip:
    - pyinotify
    - netifaces
    - setproctitle
    - imjoy==0.11.16
    - imjoy-elfinder==0.1.61